/*
 * IotaService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.affinidi.tdk.iota.client.models;

import com.affinidi.tdk.iota.client.models.AwsExchangeCredentialsProjectTokenOKCredentials;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AwsExchangeCredentialsOK
 */
class AwsExchangeCredentialsOKTest {
    private final AwsExchangeCredentialsOK model = new AwsExchangeCredentialsOK();

    /**
     * Model tests for AwsExchangeCredentialsOK
     */
    @Test
    void testAwsExchangeCredentialsOK() {
        // TODO: test AwsExchangeCredentialsOK
    }

    /**
     * Test the property 'connectionClientId'
     */
    @Test
    void connectionClientIdTest() {
        // TODO: test connectionClientId
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    void credentialsTest() {
        // TODO: test credentials
    }

}
