/*
 * IotaService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.iota.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InitiateDataSharingRequestInput
 */
public class InitiateDataSharingRequestInputTest {
    private final InitiateDataSharingRequestInput model = new InitiateDataSharingRequestInput();

    /**
     * Model tests for InitiateDataSharingRequestInput
     */
    @Test
    public void testInitiateDataSharingRequestInput() {
        // TODO: test InitiateDataSharingRequestInput
    }

    /**
     * Test the property 'queryId'
     */
    @Test
    public void queryIdTest() {
        // TODO: test queryId
    }

    /**
     * Test the property 'correlationId'
     */
    @Test
    public void correlationIdTest() {
        // TODO: test correlationId
    }

    /**
     * Test the property 'tokenMaxAge'
     */
    @Test
    public void tokenMaxAgeTest() {
        // TODO: test tokenMaxAge
    }

    /**
     * Test the property 'nonce'
     */
    @Test
    public void nonceTest() {
        // TODO: test nonce
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'configurationId'
     */
    @Test
    public void configurationIdTest() {
        // TODO: test configurationId
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

}
