/*
 * IotaService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.iota.client.models;

import com.affinidi.tdk.iota.client.models.ConsentDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListLoggedConsentsOK
 */
public class ListLoggedConsentsOKTest {
    private final ListLoggedConsentsOK model = new ListLoggedConsentsOK();

    /**
     * Model tests for ListLoggedConsentsOK
     */
    @Test
    public void testListLoggedConsentsOK() {
        // TODO: test ListLoggedConsentsOK
    }

    /**
     * Test the property 'consents'
     */
    @Test
    public void consentsTest() {
        // TODO: test consents
    }

    /**
     * Test the property 'lastEvaluatedKey'
     */
    @Test
    public void lastEvaluatedKeyTest() {
        // TODO: test lastEvaluatedKey
    }

}
