/*
 * IotaService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.iota.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdatePexQueryInput
 */
public class UpdatePexQueryInputTest {
    private final UpdatePexQueryInput model = new UpdatePexQueryInput();

    /**
     * Model tests for UpdatePexQueryInput
     */
    @Test
    public void testUpdatePexQueryInput() {
        // TODO: test UpdatePexQueryInput
    }

    /**
     * Test the property 'vpDefinition'
     */
    @Test
    public void vpDefinitionTest() {
        // TODO: test vpDefinition
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
