name: affinidi_consumer_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  affinidi_common:
    path: ../affinidi_common

  # TODO: remove this dependency
  basic_token_provider:
    path: ../basic_token_provider
  affinidi_cryptography_service:
    path: ../affinidi_cryptography_service

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
