name: affinidi_tdk_consumer_auth_provider
description: Auth provider that allows creating consumer scoped tokens to access Affinidi Vault services
version: 4.0.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.0.0
  jwt_decoder: ^2.0.1
  bip32: ^2.0.0
  web3dart: ^2.7.3
  base_codecs: ^1.0.1
  uuid: ^4.5.1
  crypto: ^3.0.6
  ssi: 1.0.0-dev.22
  dio: ^5.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
