name: affinidi_tdk_consumer_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.0.0
  affinidi_tdk_cryptography: ^1.0.0
  jwt_decoder: ^2.0.1
  bip32: ^2.0.0
  web3dart: ^2.7.3
  base_codecs: ^1.0.1
  uuid: ^4.5.1
  crypto: ^3.0.6
  dio: ^5.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4
