name: affinidi_tdk_consumer_auth_provider
description: Auth provider that allows creating consumer scoped tokens to access Affinidi Vault services
version: 4.4.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.6.0
  base_codecs: ^1.0.1
  bip32_plus: ^1.0.0
  crypto: ^3.0.6
  dio: ^5.7.0
  jwt_decoder: ^2.0.1
  ssi: ^1.0.0
  uuid: ^4.5.1
  web3dart: ^3.0.0

dev_dependencies:
  affinidi_tdk_test_utilities: 1.0.0-dev.3
  dart_flutter_team_lints: ^3.2.1
  test: ^1.24.0
