name: affinidi_tdk_test_utilities
description: The Affinidi TDK - Utilities package provides the libraries to mock requests for testing.
version: 1.1.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dio: ^5.8.0+1
  http_mock_adapter: ^0.6.1

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  test: ^1.24.0
