name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/dart/common
  - packages/dart/cryptography
  - packages/dart/auth_provider
  - packages/dart/consumer_auth_provider
  - packages/dart/consumer_auth_provider/example
  - packages/dart/test_utilities
  - libs/dart/seed_cryptography
  - libs/dart/iota_core
  - tests/integration/dart
