name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/dart/common
  - packages/dart/common/example
  - packages/dart/cryptography
  - packages/dart/auth_provider
  - packages/dart/consumer_auth_provider
  - packages/dart/consumer_auth_provider/example
  - packages/dart/test_utilities
  - packages/dart/vault_data_manager
  - packages/dart/vault_edge_provider
  - libs/dart/claim_verifiable_credential
  - libs/dart/iota_core
  - libs/dart/vault
  - libs/dart/vault/example
  - libs/dart/vault_flutter_utils
  - libs/dart/vault_flutter_utils/example/flutter_secure_storage
