# coding: utf-8

"""
    IotaService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from affinidi_tdk_iota_client.models.create_iota_configuration_input import CreateIotaConfigurationInput  # noqa: E501

class TestCreateIotaConfigurationInput(unittest.TestCase):
    """CreateIotaConfigurationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIotaConfigurationInput:
        """Test CreateIotaConfigurationInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIotaConfigurationInput`
        """
        model = CreateIotaConfigurationInput()  # noqa: E501
        if include_optional:
            return CreateIotaConfigurationInput(
                name = '',
                description = '',
                wallet_ari = '',
                iota_response_webhook_url = '',
                enable_verification = True,
                enable_consent_audit_log = True,
                token_max_age = 1,
                client_metadata = { },
                mode = 'websocket',
                redirect_uris = [
                    ''
                    ],
                enable_idv_providers = True
            )
        else:
            return CreateIotaConfigurationInput(
                name = '',
                wallet_ari = '',
                enable_verification = True,
                enable_consent_audit_log = True,
                client_metadata = { },
        )
        """

    def testCreateIotaConfigurationInput(self):
        """Test CreateIotaConfigurationInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
