name: common_example
description: Affinidi TDK Common package example
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.5.1
  affinidi_tdk_credential_issuance_client: ^1.9.0
  affinidi_tdk_iota_client: ^1.6.0
