name: affinidi_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.12.0
  http: ^1.1.0
  uuid: ^4.5.1
  affinidi_common:
    path: ../affinidi_common

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
