# coding: utf-8

"""
    VaultFileSystem

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from affinidi_tdk_vault_data_manager_client.models.create_node_ok import CreateNodeOK  # noqa: E501

class TestCreateNodeOK(unittest.TestCase):
    """CreateNodeOK unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNodeOK:
        """Test CreateNodeOK
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNodeOK`
        """
        model = CreateNodeOK()  # noqa: E501
        if include_optional:
            return CreateNodeOK(
                node_id = '',
                url = '',
                link = '',
                fields = { }
            )
        else:
            return CreateNodeOK(
                node_id = '',
        )
        """

    def testCreateNodeOK(self):
        """Test CreateNodeOK"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
