/*
 * CloudWalletEssentials
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.wallets.client.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SignCredentialsDm2SdJwtInputDto
 */
class SignCredentialsDm2SdJwtInputDtoTest {
    private final SignCredentialsDm2SdJwtInputDto model = new SignCredentialsDm2SdJwtInputDto();

    /**
     * Model tests for SignCredentialsDm2SdJwtInputDto
     */
    @Test
    void testSignCredentialsDm2SdJwtInputDto() {
        // TODO: test SignCredentialsDm2SdJwtInputDto
    }

    /**
     * Test the property 'unsignedCredential'
     */
    @Test
    void unsignedCredentialTest() {
        // TODO: test unsignedCredential
    }

    /**
     * Test the property 'revocable'
     */
    @Test
    void revocableTest() {
        // TODO: test revocable
    }

    /**
     * Test the property 'disclosureFrame'
     */
    @Test
    void disclosureFrameTest() {
        // TODO: test disclosureFrame
    }

}
