name: affinidi_tdk_test_utilities
description: Affinidi TDK test utilities
version: 1.0.0-dev.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
