name: basic_token_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  bip32: ^2.0.0
  web3dart: ^2.7.3
  base_codecs: ^1.0.1
  uuid: ^4.5.1
  crypto: ^3.0.6
  dio: ^5.7.0
  affinidi_tdk_common:
    path: ../common

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
