# coding: utf-8

"""
    OidcVpAdapterBackend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from affinidi_tdk_login_configuration_client.models.invalid_claim_context_error import InvalidClaimContextError
from affinidi_tdk_login_configuration_client.models.invalid_parameter_error import InvalidParameterError
from affinidi_tdk_login_configuration_client.models.invalid_vp_token_creation_time_error import InvalidVPTokenCreationTimeError
from affinidi_tdk_login_configuration_client.models.vp_token_validation_error import VPTokenValidationError
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

INLINEOBJECT_ONE_OF_SCHEMAS = ["InvalidClaimContextError", "InvalidParameterError", "InvalidVPTokenCreationTimeError", "VPTokenValidationError"]

class InlineObject(BaseModel):
    """
    InlineObject
    """
    # data type: InvalidParameterError
    oneof_schema_1_validator: Optional[InvalidParameterError] = None
    # data type: VPTokenValidationError
    oneof_schema_2_validator: Optional[VPTokenValidationError] = None
    # data type: InvalidClaimContextError
    oneof_schema_3_validator: Optional[InvalidClaimContextError] = None
    # data type: InvalidVPTokenCreationTimeError
    oneof_schema_4_validator: Optional[InvalidVPTokenCreationTimeError] = None
    if TYPE_CHECKING:
        actual_instance: Union[InvalidClaimContextError, InvalidParameterError, InvalidVPTokenCreationTimeError, VPTokenValidationError]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(INLINEOBJECT_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = InlineObject.construct()
        error_messages = []
        match = 0
        # validate data type: InvalidParameterError
        if not isinstance(v, InvalidParameterError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InvalidParameterError`")
        else:
            match += 1
        # validate data type: VPTokenValidationError
        if not isinstance(v, VPTokenValidationError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VPTokenValidationError`")
        else:
            match += 1
        # validate data type: InvalidClaimContextError
        if not isinstance(v, InvalidClaimContextError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InvalidClaimContextError`")
        else:
            match += 1
        # validate data type: InvalidVPTokenCreationTimeError
        if not isinstance(v, InvalidVPTokenCreationTimeError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InvalidVPTokenCreationTimeError`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in InlineObject with oneOf schemas: InvalidClaimContextError, InvalidParameterError, InvalidVPTokenCreationTimeError, VPTokenValidationError. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in InlineObject with oneOf schemas: InvalidClaimContextError, InvalidParameterError, InvalidVPTokenCreationTimeError, VPTokenValidationError. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> InlineObject:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> InlineObject:
        """Returns the object represented by the json string"""
        instance = InlineObject.construct()
        error_messages = []
        match = 0

        # deserialize data into InvalidParameterError
        try:
            instance.actual_instance = InvalidParameterError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VPTokenValidationError
        try:
            instance.actual_instance = VPTokenValidationError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InvalidClaimContextError
        try:
            instance.actual_instance = InvalidClaimContextError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InvalidVPTokenCreationTimeError
        try:
            instance.actual_instance = InvalidVPTokenCreationTimeError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into InlineObject with oneOf schemas: InvalidClaimContextError, InvalidParameterError, InvalidVPTokenCreationTimeError, VPTokenValidationError. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into InlineObject with oneOf schemas: InvalidClaimContextError, InvalidParameterError, InvalidVPTokenCreationTimeError, VPTokenValidationError. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


