# coding: utf-8

"""
    OidcVpAdapterBackend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from affinidi_tdk_login_configuration_client.models.service_error_response_details_inner import ServiceErrorResponseDetailsInner

class ServiceErrorResponse(BaseModel):
    """
    Service Error Response  # noqa: E501
    """
    debug_id: StrictStr = Field(default=..., alias="debugId", description="unique id for correlating this specific error to logs")
    name: StrictStr = Field(default=..., description="name of the error")
    code: StrictStr = Field(default=..., description="backwards compatible Affinidi error code")
    details: Optional[conlist(ServiceErrorResponseDetailsInner)] = Field(default=None, description="error details")
    __properties = ["debugId", "name", "code", "details"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceErrorResponse:
        """Create an instance of ServiceErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in details (list)
        _items = []
        if self.details:
            for _item in self.details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['details'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceErrorResponse:
        """Create an instance of ServiceErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceErrorResponse.parse_obj(obj)

        _obj = ServiceErrorResponse.parse_obj({
            "debug_id": obj.get("debugId"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "details": [ServiceErrorResponseDetailsInner.from_dict(_item) for _item in obj.get("details")] if obj.get("details") is not None else None
        })
        return _obj


