# coding: utf-8

"""
    CloudWalletEssentials

    Cloud Wallet For Enterprise Structure

    The version of the OpenAPI document: 1.0.0
    Contact: nucleus.team@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from affinidi_tdk_client_cwe.models.did_key_input_params import DidKeyInputParams  # noqa: E501

class TestDidKeyInputParams(unittest.TestCase):
    """DidKeyInputParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DidKeyInputParams:
        """Test DidKeyInputParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DidKeyInputParams`
        """
        model = DidKeyInputParams()  # noqa: E501
        if include_optional:
            return DidKeyInputParams(
                did_method = 'key'
            )
        else:
            return DidKeyInputParams(
        )
        """

    def testDidKeyInputParams(self):
        """Test DidKeyInputParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
