# coding: utf-8

"""
    Iam

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from affinidi_tdk_iam_client.api.well_known_api import WellKnownApi  # noqa: E501


class TestWellKnownApi(unittest.TestCase):
    """WellKnownApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WellKnownApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_well_known_did(self) -> None:
        """Test case for get_well_known_did

        """
        pass

    def test_get_well_known_jwks(self) -> None:
        """Test case for get_well_known_jwks

        """
        pass


if __name__ == '__main__':
    unittest.main()
