# coding: utf-8

"""
    CredentialIssuanceService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class ClaimedCredentialListResponse(BaseModel):
    """
    List of claimed credential  # noqa: E501
    """
    credentials: Optional[conlist(Dict[str, Any])] = Field(default=None, description="list of credentials")
    last_evaluated_key: Optional[StrictStr] = Field(default=None, alias="lastEvaluatedKey", description="for pagination to fetch next set of records")
    __properties = ["credentials", "lastEvaluatedKey"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClaimedCredentialListResponse:
        """Create an instance of ClaimedCredentialListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClaimedCredentialListResponse:
        """Create an instance of ClaimedCredentialListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClaimedCredentialListResponse.parse_obj(obj)

        _obj = ClaimedCredentialListResponse.parse_obj({
            "credentials": obj.get("credentials"),
            "last_evaluated_key": obj.get("lastEvaluatedKey")
        })
        return _obj


