name: affinidi_tdk_auth_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.0.0
  dart_jsonwebtoken: ^2.12.0
  pointycastle: ^3.9.1
  http: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
  mocktail: ^1.0.4
  path: ^1.9.1
