name: affinidi_tdk_mediator_client
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  didcomm: ^2.0.3
  dio: ^5.9.0
  ssi: ^2.15.1
  uuid: ^4.5.1

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  lints: ^5.0.0
