name: affinidi_tdk_mediator_client
description: Affinidi TDK dart client for Affinidi MEDIATOR package provides libraries and tools to create a mediator service that handles and routes signed abd encrypted messages sent between participants (e.g., users, organisations, another mediator, or even AI agents).
version: 1.0.0
homepage: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  didcomm: ^1.0.0-dev.14
  dio: ^5.9.0
  ssi: ^2.12.4
  uuid: ^4.5.1

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  lints: ^5.0.0
