# coding: utf-8

"""
    CloudWalletEssentials

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr, validator

class UpdateServiceEndpointInput(BaseModel):
    """
    Input for updating a service endpoint  # noqa: E501
    """
    name: Optional[constr(strict=True)] = Field(default=None, description="Alphanumeric string with common punctuation (max 100 characters)")
    description: Optional[constr(strict=True)] = Field(default=None, description="Alphanumeric string with common punctuation (max 500 characters)")
    url: Optional[constr(strict=True, max_length=2048)] = Field(default=None, description="HTTP or HTTPS URL")
    __properties = ["name", "description", "url"]

    @validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9\s\-_.,:#\'()]{0,99}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9][a-zA-Z0-9\s\-_.,:#'()]{0,99}$/")
        return value

    @validator('description')
    def description_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9\s\-_.,:#\'()]{0,499}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9][a-zA-Z0-9\s\-_.,:#'()]{0,499}$/")
        return value

    @validator('url')
    def url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^https?:\/\/[a-zA-Z0-9\-._~:\/?#[\]@!$&\'()*+,;=%]+$", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\/[a-zA-Z0-9\-._~:\/?#[\]@!$&'()*+,;=%]+$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateServiceEndpointInput:
        """Create an instance of UpdateServiceEndpointInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateServiceEndpointInput:
        """Create an instance of UpdateServiceEndpointInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateServiceEndpointInput.parse_obj(obj)

        _obj = UpdateServiceEndpointInput.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "url": obj.get("url")
        })
        return _obj


