name: avmp_cryptography_service

version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bs58: ^1.0.2
  convert: ^3.1.1
  crypto: ^3.0.3
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  dart_jsonwebtoken: ^2.14.0
  jwt_decoder: ^2.0.1
  pointycastle: ^3.9.1
  secp256k1: ^0.3.0
