/*
 * CredentialIssuanceService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.credential.issuance.client.models;

import com.affinidi.tdk.credential.issuance.client.models.StartIssuanceInputDataInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StartIssuanceInput
 */
public class StartIssuanceInputTest {
    private final StartIssuanceInput model = new StartIssuanceInput();

    /**
     * Model tests for StartIssuanceInput
     */
    @Test
    public void testStartIssuanceInput() {
        // TODO: test StartIssuanceInput
    }

    /**
     * Test the property 'claimMode'
     */
    @Test
    public void claimModeTest() {
        // TODO: test claimMode
    }

    /**
     * Test the property 'holderDid'
     */
    @Test
    public void holderDidTest() {
        // TODO: test holderDid
    }

    /**
     * Test the property 'issuanceId'
     */
    @Test
    public void issuanceIdTest() {
        // TODO: test issuanceId
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
