name: affinidi_tdk_atm_client
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/affinidi/affinidi-tdk
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  affinidi_tdk_mediator_client:
    path: ../mediator_client
  json_annotation: ^4.9.0
  ssi: ^2.12.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.11
  dart_flutter_team_lints: ^3.5.2
  json_serializable: ^6.9.5
  lints: ^6.0.0
  path: ^1.9.1
  retry: ^3.1.2
  test: ^1.24.0
