name: atm_client
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  # TODO: reference version from pub dev
  mediator_client:
    path: ../mediator_client
  uuid: ^4.5.1
  # TODO: upgrade didcomm package to the latest ssi first, and then use the latest ssi version here
  ssi: 2.10.3

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.24.0
