name: atm_client
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/affinidi/affinidi-tdk
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  # TODO: reference version from pub dev
  mediator_client:
    path: ../mediator_client
  ssi: ^2.12.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.11
  dart_flutter_team_lints: ^3.5.2
  json_serializable: ^6.9.5
  lints: ^6.0.0
  mockito: ^5.4.4
  path: ^1.9.1
  test: ^1.24.0
