name: affinidi_tdk_cryptography
description: Cryptography package for Affinidi TDK that provides cryptographic functionalities for secure token management, encryption and decryption.
version: 2.0.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  bs58: ^1.0.2
  convert: ^3.1.1
  crypto: ^3.0.3
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^2.14.0
  jwt_decoder: ^2.0.1
  pointycastle: ^3.9.1
  secp256k1: ^0.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
