name: affinidi_vault_edge_provider
description: The Affinidi TDK - Vault Edge Provider manages files and credentials in a local storage.
version: 1.0.0-dev.1
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  test: ^1.24.0
