/*
 * VaultFileSystem
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@affinidi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.affinidi.tdk.vault.data.manager.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RestoreNodeFromTrashbin
 */
public class RestoreNodeFromTrashbinTest {
    private final RestoreNodeFromTrashbin model = new RestoreNodeFromTrashbin();

    /**
     * Model tests for RestoreNodeFromTrashbin
     */
    @Test
    public void testRestoreNodeFromTrashbin() {
        // TODO: test RestoreNodeFromTrashbin
    }

    /**
     * Test the property 'restoreToProfileId'
     */
    @Test
    public void restoreToProfileIdTest() {
        // TODO: test restoreToProfileId
    }

}
