name: affinidi_tdk_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
