name: affinidi_tdk_common
description: Common package for Affinidi TDK with Vault utilities to generate claim and share links
version: 1.6.0
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  lints: ^5.0.0
  test: ^1.24.0
