# coding: utf-8

"""
    IotaService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@affinidi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class CallbackResponseOKRedirectResponse(BaseModel):
    """
    CallbackResponseOKRedirectResponse
    """
    redirect_uri: Optional[StrictStr] = Field(default=None, alias="redirectUri", description="the configured redirect url where vault will redirect")
    response_code: Optional[StrictStr] = Field(default=None, alias="responseCode", description="Code which will be used to retrieve data along with transactionId")
    __properties = ["redirectUri", "responseCode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CallbackResponseOKRedirectResponse:
        """Create an instance of CallbackResponseOKRedirectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CallbackResponseOKRedirectResponse:
        """Create an instance of CallbackResponseOKRedirectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CallbackResponseOKRedirectResponse.parse_obj(obj)

        _obj = CallbackResponseOKRedirectResponse.parse_obj({
            "redirect_uri": obj.get("redirectUri"),
            "response_code": obj.get("responseCode")
        })
        return _obj


