name: vdip_browser_context_flutter
description: VDIP browser context switch example with Veriff integration
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  affinidi_tdk_didcomm_client:
    path: ../../
  affinidi_tdk_mediator_client:
    path: ../../../mediator_client
  ssi: ^2.12.4
  uuid: ^4.5.1
  dio: ^5.7.0
  veriff_flutter: ^5.3.0
  path: ^1.9.1

dependency_overrides:
  meta: 1.16.0
