name: affinidi_tdk_vault_edge_drift_provider
description: A library to manage Vault CRUD operations on a Drift database
version: 1.0.0-dev.2
repository: https://github.com/affinidi/affinidi-tdk

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^1.6.0
  affinidi_tdk_vault_edge_provider: ^1.0.0-dev.2
  clock: ^1.1.1
  drift: ^2.23.1 # note using this version because it's compatible with analyzer version lower than 7.0.0 required by flutter_test included with flutter 3.27.0
  path: ^1.8.3
  sqlite3: ^2.7.6
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  dart_flutter_team_lints: ^3.2.1
  drift_dev: ^2.23.1 # note using this version because it's compatible with analyzer version lower than 7.0.0 required by flutter_test included with flutter 3.27.0
  test: ^1.24.0

dependency_overrides:
  file: ^6.1.3
