name: Manual integration tests for Typescript vs DEV environment

on:
  workflow_dispatch: # Manual trigger

permissions:
  actions: read
  contents: read

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install test deps (due to relative paths)
        run: npm ci
        working-directory: tests/integration/typescript

      - name: Cache testing env file
        uses: actions/cache@v4
        id: testing-env-cache
        with:
          path: tests/.env
          key: ${{ runner.os }}-testing-env-${{ hashFiles('tests/.env') }}

      - if: ${{ steps.testing-env-cache.outputs.cache-hit != 'true' }}
        name: Prepare environment file
        env:
          TESTING_ENV_FILE_CONTENT: ${{ secrets.TESTING_ENV_FILE_CONTENT }}
        run: echo $TESTING_ENV_FILE_CONTENT | base64 --decode > tests/.env

      - name: Run integration tests
        run: AFFINIDI_TDK_ENVIRONMENT=dev npm run test:internal
        working-directory: tests/integration/typescript
