name: Integration tests for Dart

on:
  push:
    branches-ignore:
      - main
    paths: # run if any of below was changed
      - 'clients/dart/**'
      - 'packages/dart/**'
      - 'libs/dart/**'
      - 'tests/integration/dart/**'

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.0

      - name: Install dependencies
        run: dart pub get
        working-directory: tests/integration/dart

      - name: Cache testing env file
        uses: actions/cache@v4
        id: testing-env-cache
        with:
          path: tests/.env
          key: ${{ runner.os }}-testing-env-${{ hashFiles('tests/.env') }}

      - if: ${{ steps.testing-env-cache.outputs.cache-hit != 'true' }}
        name: Prepare environment file
        env:
          TESTING_ENV_FILE_CONTENT: ${{ secrets.TESTING_ENV_FILE_CONTENT }}
        run: echo $TESTING_ENV_FILE_CONTENT | base64 --decode > tests/.env

      - name: Run integration tests
        env:
          TEST_MEDIATOR_DID: ${{ vars.TEST_MEDIATOR_DID }}
          TEST_MEDIATOR_WITH_ACL_DID: ${{ vars.TEST_MEDIATOR_WITH_ACL_DID }}
          TEST_ALICE_PRIVATE_KEY_PEM: ${{ vars.TEST_ALICE_PRIVATE_KEY_PEM }}
          TEST_BOB_PRIVATE_KEY_PEM: ${{ vars.TEST_BOB_PRIVATE_KEY_PEM }}
        run: dart test --concurrency=1
        working-directory: tests/integration/dart