name: release

on:
  push:
    branches:
      - 'main'

jobs:
  security:
    permissions:
      contents: read
      checks: read
      statuses: read
      security-events: write
    uses: affinidi/pipeline-security/.github/workflows/security-scanners.yml@feat/check-inherit
    with:
      config-path: .github/labeler.yml
    secrets: inherit
  release:
    concurrency: release
    runs-on: ubuntu-latest
    environment: main
    needs:
      - security
    steps:
      - name: Generate token from app token #https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.RELEASE_BOT_PKEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      # Setup cache, npm
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@affinidi-tdk'
      - run: npm ci
      # Generate tag/changelog
      # setting parallel higher than one might cause problems with locking git repo
      - run: npx nx run-many  -t semantic-release --parallel=false
        name: semantic release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to npm
      - run: |
          npx nx release publish --verbose
        name: release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
