name: release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup cache, npm
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@affinidi-tdk'

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.0

      - run: npm ci
      # Generate tag/changelog with semantic release
      # setting parallel higher than one might cause problems with locking git repo
      - run: npx nx affected  -t semantic-release --parallel=false --base=$BASE_SHA --head=HEAD
        name: semantic release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          BASE_SHA: ${{ github.event.before }}
