name: release

on:
  workflow_run:
    workflows: [security]
    types: [completed]
    branches: [main]


jobs:
  release:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: npm ci

      # Generate tag/changelog
      - run: npx nx run-many  -t semantic-release --parallel 1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Publish to npm
      # setting parallel higher than one might cause problems with locking git repo
      - run: npx nx release publish --verbose
        with:
          node-version: 18
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
