name: security

on:
  push:
    branches:
      - 'main' 
  pull_request:

jobs:
  security:
    permissions:
      contents: read
      checks: read
      statuses: read
      security-events: write
    uses: affinidi/pipeline-security/.github/workflows/security-scanners.yml@feat/check-inherit
    with:
      config-path: .github/labeler.yml
    secrets: inherit
