name: Unit tests for Dart

on:
  push:
    branches-ignore:
      - main
    paths: # run if any of below was changed
      - 'clients/dart/**'

jobs:
  unit_tests_didcomm_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.0

      - name: Install dependencies
        run: flutter pub get
        working-directory: clients/dart/didcomm/vdsp_client

      - name: Run unit tests
        run: dart test
        working-directory: clients/dart/didcomm/vdsp_client